version: "3.0"

set: ['e', 'u', 'pipefail']
shopt: ['globstar']

dotenv: ['.env']

env:
  TLD: "{{.ROOT_DIR}}"
  APP:
    sh: echo "${APP_NAME:-gopappy}"

vars:

includes:
  docker:
    taskfile: ./taskfiles/docker.yml
  poetry:
    taskfile: ./taskfiles/poetry.yml

tasks:
  default:
    desc: "Default task"
    cmds:
      - task --list

  install:
    desc: "Install project dependencies"
    dir: "{{.TLD}}"
    cmds:
      - ./bootstrap

  pre-commit:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run --all-files
