name: Release Please

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.py'
      - '**/*.sh'
      - '**/*.md'
  workflow_run:
    workflows: ["Run pytest"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Release with release-please
        uses: google-github-actions/release-please-action@v4
        with:
          # PAT with write access to the repository
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json
